### ISSUE TITLE
Keras models loading error

### ISSUE THREAD

**Issue by MichaelMonashev** [ProGamerGov/neural-dream#5]
Try to load efficientnet keras model and get this error:
```
$ python3 neural_dream.py -model_file ~/1111/zzz.h5 -model_type keras -print_layers
Traceback (most recent call last):
  File "neural_dream.py", line 793, in <module>
    main()
  File "neural_dream.py", line 121, in main
    cnn, layerList = loadCaffemodel(params.model_file, params.pooling, params.gpu, params.disable_check, True)
  File "/home/xxxx/1111/neural-dream/neural_dream/CaffeLoader.py", line 410, in loadCaffemodel
    cnn, layerList = modelSelector(str(model_file).lower(), pooling)
  File "/home/xxxx/1111/neural-dream/neural_dream/CaffeLoader.py", line 370, in modelSelector
    raise ValueError("Model architecture not recognized.")
ValueError: Model architecture not recognized.
```

How to fix it?

**Comment by ProGamerGov** [comment]
@MichaelMonashev You'll have to convert the model to PyTorch's `.pth` format first, with something like [MMdnn](https://github.com/microsoft/MMdnn). If the model is different than any of the exiting models in terms of layers, channels, or anything like that, you have to create a class for it. 

The existing model classes that I had to create for Inception, Resnet, and GoogleNet can be found here: https://github.com/ProGamerGov/neural-dream/tree/master/neural_dream/models. The VGG, NIN, and Official PyTorch model classes and names are located in the [CaffeLoader.py](https://github.com/ProGamerGov/neural-dream/blob/master/neural_dream/CaffeLoader.py) file, but I should probably move them for the sake of readability. Other supported models are listed here: https://github.com/ProGamerGov/neural-dream/wiki/Models

**If it's different that the existing model classes:**

Copy the model class file produced by MMdnn and remove the unneeded stuff from the copy. I use Notepad++ to modify a copy of the PyTorch class file that MMdnn produces, and then I load test my new class with [this script](https://gist.github.com/ProGamerGov/1c9bc91f8f426834031e07b8b8dafb52), that also saves the model as a state dict. You can then use the [helper_layers.py](https://github.com/ProGamerGov/neural-dream/blob/master/neural_dream/helper_layers.py) classes to replace torch.nn.functional, addition, and other layers that the model itself does not have, so that these layers are able to selected with hooks. 

If the model is similar enough to an existing class file, then you can just copy or modify it. 

Once you have a working model class, then you have to add the model's file name to the [model selector function](https://github.com/ProGamerGov/neural-dream/blob/master/neural_dream/CaffeLoader.py#L310-L371) .

For ResNet, GoogleNet, and Inception models, you don't need to worry about the layer name dicts and can leave them blank. The layer names are the layer class names inside the model class.

**If it's the same as one of the existing classes:**

Then all you need to do is change the `.pth` model's name to something that the [model selector function](https://github.com/ProGamerGov/neural-dream/blob/master/neural_dream/CaffeLoader.py#L310-L371) can detect. PyTorch doesn't have prototxt files like Torch7, so I've been using the model's name to detect which class I need to use in order to load it. 


If you have any questions, I can try to answer them.

**Comment by ProGamerGov** [comment]
I'm going to close this issue as it appears to be resolved.
